FROM node:18.16.1 as build-stage

RUN echo 'transferrring context ...' >> /build-log.txt
WORKDIR /app
COPY ./src .

# Run build
RUN echo 'running build script ...' >> /build-log.txt

WORKDIR ./model/core
RUN npm install

WORKDIR ../server
RUN npm install

WORKDIR ../client
RUN npm install

WORKDIR ../../server
RUN npm install

WORKDIR ../ui/browser-react
RUN npm install

WORKDIR ../../../

RUN echo 'starting final stage ...' >> /build-log.txt

FROM node:18.16.1-alpine as final-stage

LABEL name="web-application-quickstart"
LABEL version="0.1"
LABEL maintaner="webapplicationquickstart@strisys.com"
EXPOSE 3000

WORKDIR /app
COPY --from=build-stage /build-log.txt .
COPY --from=build-stage /app .
RUN ls -l >> ./build-log.txt
# CMD cat ./build-log.txt
WORKDIR /app/server
CMD ["npm", "start"]